// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGOVCOs-6v7Y_trurwJFxhdglF8KQpWlo',
    appId: '1:221397392431:web:81f17607b7aed78e5cfada',
    messagingSenderId: '221397392431',
    projectId: 'swayastudio',
    authDomain: 'swayastudio.firebaseapp.com',
    storageBucket: 'swayastudio.firebasestorage.app',
    measurementId: 'G-15KV41NYRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3JQpqJ473Gws0I_CrPZvBIWQctxvBrSE',
    appId: '1:221397392431:android:21058019e66d44e35cfada',
    messagingSenderId: '221397392431',
    projectId: 'swayastudio',
    storageBucket: 'swayastudio.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcSh4gBZCC4xyggJ8-K0OwBkXdnZibIA',
    appId: '1:221397392431:ios:15c142ca0fa2bfd75cfada',
    messagingSenderId: '221397392431',
    projectId: 'swayastudio',
    storageBucket: 'swayastudio.firebasestorage.app',
    iosClientId: '221397392431-612h9ic9uv7l01d505d9jh3mlj01o52h.apps.googleusercontent.com',
    iosBundleId: 'com.swaya.swayaApp',
  );
}
